services:
  database:
    image: postgres
    env_file: .env
    restart: always
    volumes:
      - ./pg_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DATABASE} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    command: npx jest --config ./jest.config.ts --passWithNoTests --runInBand --detectOpenHandles
    restart: always
    env_file: .env
    volumes:
      - ./server:/app
    depends_on:
      database:
        condition: service_healthy